// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAlutD4DfcDNvrStCJ3Zzoh1dLSW6X5iOc",
  authDomain: "instaclone-4a533.firebaseapp.com",
  projectId: "instaclone-4a533",
  storageBucket: "instaclone-4a533.firebasestorage.app",
  messagingSenderId: "875157500588",
  appId: "1:875157500588:web:398633337f420e78356509",
  measurementId: "G-0XH4WT80VX"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXah3fpOts7e_9k1O1uRl0QqlxreYNv0',
    appId: '1:706148437269:android:0527ecda07f62822d76d1c',
    messagingSenderId: '706148437269',
    projectId: 'madgram-f10ae',
    storageBucket: 'madgram-f10ae.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoIUD0MfxM67DorJXxymlGLd9I3-dlrrw',
    appId: '1:706148437269:web:d5be65989a702ed1d76d1c',
    messagingSenderId: '706148437269',
    projectId: 'madgram-f10ae',
    authDomain: 'madgram-f10ae.firebaseapp.com',
    storageBucket: 'madgram-f10ae.firebasestorage.app',
    measurementId: 'G-RNVGVHDKFC',
  );
}
